# Generated by Django 4.2.7 on 2025-09-20 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventes', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat fournisseur'), ('frais', 'Frais généraux'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('electricite', 'Électricité'), ('telephone', 'Téléphone/Internet'), ('transport', 'Transport'), ('publicite', 'Publicité'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_valeur', models.DateField(blank=True, help_text='Date de valeur de la transaction', null=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='achats.achat')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ventes.vente')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CaisseFonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ouverture', 'Ouverture caisse'), ('fermeture', 'Fermeture caisse'), ('approvisionnement', 'Approvisionnement'), ('retrait', 'Retrait')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_avant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_apres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement caisse',
                'verbose_name_plural': 'Mouvements caisse',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('montant_prevu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('categories', models.CharField(help_text='Catégories concernées (séparées par des virgules)', max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
