# Generated by Django 4.2.7 on 2025-09-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caissefonds',
            options={},
        ),
        migrations.AddField(
            model_name='caissefonds',
            name='categorie_depense',
            field=models.CharField(choices=[('vente', 'Vente'), ('achat', 'Achat fournisseur'), ('frais', 'Frais généraux'), ('salaire', 'Salaire'), ('loyer', 'Loyer'), ('electricite', 'Électricité'), ('telephone', 'Téléphone/Internet'), ('transport', 'Transport'), ('publicite', 'Publicité'), ('autre', 'Autre')], default='autre', help_text='Catégorie utilisée pour la Transaction générée', max_length=20),
        ),
    ]
