# Generated by Django 5.1.5 on 2025-12-13 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_vente_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venteitem',
            name='prix_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente standard du produit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_vendeur', to=settings.AUTH_USER_MODEL),
        ),
    ]
