# Generated by Django 5.1.5 on 2026-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_venteitem_prix_original_alter_vente_utilisateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='statut_paiement',
            field=models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('impaye', 'Impayé')], default='impaye', max_length=20),
        ),
    ]
