# Generated by Django 4.2.7 on 2025-09-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('manager', 'Gestionnaire'), ('cashier', 'Caissier')], default='Administrateur', max_length=20),
        ),
    ]
